create table if not exists public.feedbacks (
  id bigint generated by default as identity primary key,
  name text not null,
  user_type text not null check (user_type in ('Aluno', 'Pai', 'Mãe', 'Responsável')),
  team_time text,
  rating integer not null check (rating between 1 and 5),
  comment text not null,
  publish_authorized boolean not null default false,
  submitted_at timestamptz not null default now(),
  status text not null default 'Pendente' check (status in ('Pendente', 'Aprovado', 'Rejeitado'))
);

create table if not exists public.submission_log (
  id bigint generated by default as identity primary key,
  ip_hash text not null,
  submitted_at bigint not null
);

create index if not exists feedbacks_public_idx
  on public.feedbacks (status, publish_authorized, submitted_at desc);

create index if not exists submission_log_rate_limit_idx
  on public.submission_log (ip_hash, submitted_at desc);

alter table public.feedbacks enable row level security;
alter table public.submission_log enable row level security;

drop policy if exists "Public can read approved feedbacks" on public.feedbacks;
create policy "Public can read approved feedbacks"
  on public.feedbacks
  for select
  using (status = 'Aprovado' and publish_authorized = true);

-- O back-end usa SUPABASE_SERVICE_ROLE_KEY, que deve ficar somente no servidor.
